# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(230, 410)
        MainWindow.setMinimumSize(QtCore.QSize(230, 410))
        MainWindow.setMaximumSize(QtCore.QSize(230, 410))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginBtn.setGeometry(QtCore.QRect(10, 10, 210, 30))
        self.loginBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.loginBtn.setObjectName("loginBtn")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(10, 340, 100, 30))
        self.addBtn.setObjectName("addBtn")
        self.watchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.watchBtn.setGeometry(QtCore.QRect(10, 370, 211, 30))
        self.watchBtn.setObjectName("watchBtn")
        self.delBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delBtn.setGeometry(QtCore.QRect(120, 340, 100, 30))
        self.delBtn.setObjectName("delBtn")
        self.channelListView = QtWidgets.QListView(self.centralwidget)
        self.channelListView.setGeometry(QtCore.QRect(10, 50, 210, 280))
        self.channelListView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.channelListView.setObjectName("channelListView")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main"))
        self.loginBtn.setText(_translate("MainWindow", " 登入"))
        self.addBtn.setText(_translate("MainWindow", "新增頻道"))
        self.watchBtn.setText(_translate("MainWindow", "開始掛台"))
        self.delBtn.setText(_translate("MainWindow", "刪除反白"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
